version: "3.8"
services:
  laravel_app:
    image: ubuntu:20.04
    container_name: nginx_php8_laravel8
    build:
      context: .
    ports:
      - "8081:8081"
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
    environment:
      TZ: Asia/Seoul
    stdin_open: true # docker run -i
    tty: true # docker run -t
  proxy:
    image: nginx
    container_name: nginx_proxy
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - laravel_app
    stdin_open: true # docker run -i
    tty: true # docker run -t
